defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
data:
  load_from: "data/diabetic_data_wtarget.csv"
  results_path : "results/"
  plot_path : "plots/"
  sensitive_attribute :
    name: 'Sex'
    protected: 'female'
  class_attribute :
    name: 'class'
    positive_value: 1 #1 or 2 / good or bad


basic:
  feature_selection : False
  exclude_sensitive_attribute : False
  split_data:
    val_data : True
    resampling_train_set : False
  split_percent : 0.2
  neighbors: 3
  focus_metric : 'fairness_parity_rate'
  condition:
    affirmative_action: true
    difference_percentage: 0
  weight:
    include_dominant_attribute: false
    second_weight: false

experiment_name: "diabetic_data_no_ada"

hydra:
  output_subdir: /data
  run:
    dir: .
  job_logging:
    disable_existing_loggers: false