defaults:
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
data:
  load_from: "../data/red_blue_dataset.csv"
  results_path : "results/"
  plot_path : "plots/"
  sensitive_attribute :
    name: 'color'
    protected: 'red'
  class_attribute :
    name: 'class'
    positive_value: 1 #1 or 2 / good or bad


basic:
  feature_selection : False
  exclude_sensitive_attribute : true
  split_data:
    val_data : True
    resampling_train_set : False
  basic_split : true
  random_train_point : false
  split_percent : 0.2
  neighbors: 3
  condition:
    affirmative_action: false
    sensitive_catches_dominant: false
    difference_percentage: 0
  weight:
    second_weight: true
experiment_name: "red_blue"
csv_to_word : true

hydra:
  output_subdir: /data
  run:
    dir: .
  job_logging:
    disable_existing_loggers: false